// <auto-generated />
using System;
using CletusReyes.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CletusReyes.Migrations
{
    [DbContext(typeof(CletusReyesDbContext))]
    [Migration("20230816004014_Add rows for users I")]
    partial class AddrowsforusersI
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CletusReyes.Models.Domain_Model.Auth.TblRoles", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = "31f16eb0-8649-4015-9edd-b179b461a2dd",
                            ConcurrencyStamp = "31f16eb0-8649-4015-9edd-b179b461a2dd",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "f71926a4-5573-4a11-bb9c-875d856cd446",
                            ConcurrencyStamp = "f71926a4-5573-4a11-bb9c-875d856cd446",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        });
                });

            modelBuilder.Entity("CletusReyes.Models.Domain_Model.Auth.TblUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "0fbcb272-5086-4b30-a6c9-66d72a9bde37",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d0b4c159-28a4-4549-8997-dfd3daf80f01",
                            Email = "brandonv@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "BRANDONV@GMAIL.COM",
                            NormalizedUserName = "BR",
                            PasswordHash = "AQAAAAIAAYagAAAAEN7In5GO6ZXZMuEVck1ROa10p35O99ff9LiOWQTyQ7udEMYHBsR3ja6fjokzlfCCDA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "CUAI6OTACIJT7M5PZNWCHLP22PLTZAPC",
                            TwoFactorEnabled = false,
                            UserName = "br"
                        },
                        new
                        {
                            Id = "215dc03c-ef26-46a5-8031-7dec9f87928e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c8c0877f-b150-4dc9-9ecc-e8482540506d",
                            Email = "userAdmin@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "USERADMIN@GMAIL.COM",
                            NormalizedUserName = "US",
                            PasswordHash = "AQAAAAIAAYagAAAAEPTpuqL+e6zLtCCnJZc6q15xVOwdplQ0HIOX/vGQaPEOEsyNxPgTdf3NM6tZOlcG8A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "KXCSIA5K65MWJRCFUK5VYWSXY5VFHPLA",
                            TwoFactorEnabled = false,
                            UserName = "us"
                        },
                        new
                        {
                            Id = "22380616-12fd-4e2e-b86e-58c11a76ec52",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "15d949bc-9f4f-4d71-9cb8-67389f590824",
                            Email = "hassela@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "HASSELA@GMAIL.COM",
                            NormalizedUserName = "HA",
                            PasswordHash = "AQAAAAIAAYagAAAAELQKXjBfM/ccxR6zNAnWsmDi868hrY3GOpShW40PvJ5riTWfoZtzKCXjV3rvPWd5Wg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5N7VD76YPQD4FW6YUUBBCAHAHRL5AFKL",
                            TwoFactorEnabled = false,
                            UserName = "ha"
                        },
                        new
                        {
                            Id = "342d70c0-a00c-43e3-a069-36d5ed2005b5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3d705dfb-9118-4ff8-b0d7-e8a36406bd1e",
                            Email = "davids@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "DAVIDS@GMAIL.COM",
                            NormalizedUserName = "DA",
                            PasswordHash = "AQAAAAIAAYagAAAAEPWa3z1JivXSVIsH4/f9xiPATWxo/Mn4gUPN8UT/Rr3lP7GqFujw5GaApai3q1xSCQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "TMTKWNY7REES6S2GR3LMS56FO5PPSDAC",
                            TwoFactorEnabled = false,
                            UserName = "da"
                        },
                        new
                        {
                            Id = "36e4d06a-831d-4f23-b491-537f20825375",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3bd9f4ea-ffed-456c-a230-7d36262c03c4",
                            Email = "paulav@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "PAULAV@GMAIL.COM",
                            NormalizedUserName = "PA",
                            PasswordHash = "AQAAAAIAAYagAAAAEHcWTHI+/fLKYWfl9puPAkgPEDMEo7Fyk9fTvn7LTX/239SFT7dPq+YJRU2bKXykWg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "J7E6JPE4I5YPWSLOER3D47YSRZ4WIVUJ",
                            TwoFactorEnabled = false,
                            UserName = "pa"
                        },
                        new
                        {
                            Id = "3b79afd6-5b42-4685-af13-c47b20fc4b38",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3cde4d24-d01f-4e2a-828f-14a06e6bd1e2",
                            Email = "armandot@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "ARMANDOT@GMAIL.COM",
                            NormalizedUserName = "AR",
                            PasswordHash = "AQAAAAIAAYagAAAAEOlBn+tvSEUnH3UHWOKqKdljUc9vGaKbjBKJl/c9OZWbxIobXk1Cvpkb01k65bqOgg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "DNFYPMJOGCLJUJXJH5LXL7WAQFL6ZOGS",
                            TwoFactorEnabled = false,
                            UserName = "ar"
                        },
                        new
                        {
                            Id = "4523059a-0da7-412c-8e2b-d35300943dde",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "aad98d39-1e7c-42fa-9a98-e89a8c868494",
                            Email = "ivano@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "IVANO@GMAIL.COM",
                            NormalizedUserName = "IV",
                            PasswordHash = "AQAAAAIAAYagAAAAEDr3sLGMjjMRKJPwnCmh8cIt2qCcAEvJIcp7rJ0ZQ3rnihFhS54r+LVF3+OsN91GUw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "HPT5IN4VHJ4LX5DPB2ZBX6VOKUIMLBSV",
                            TwoFactorEnabled = false,
                            UserName = "iv"
                        },
                        new
                        {
                            Id = "4a8bf52a-fdba-4ebf-8996-48f3536df4e0",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f069e819-076a-454e-8ea6-415bfd1dc57e",
                            Email = "nestorp@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "NESTORP@GMAIL.COM",
                            NormalizedUserName = "NE",
                            PasswordHash = "AQAAAAIAAYagAAAAEEqILrxhTzKyoFped6EGnaW8yhDh5a7/DOKpjL1MeoiIKirauJfw/WQMR3zWhztEKQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7X33NX64SQEGL2VIKKWXC2MIESWZD5CP",
                            TwoFactorEnabled = false,
                            UserName = "ne"
                        },
                        new
                        {
                            Id = "4d9c2616-e560-4039-8208-64ce82943c6d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f8e90e5e-c074-4441-83c2-bd6da62adb7f",
                            Email = "yairt@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "YAIRT@GMAIL.COM",
                            NormalizedUserName = "YA",
                            PasswordHash = "AQAAAAIAAYagAAAAEDIxLoKzxmjR5784C/y0PTHrjiCMZxzgE7kPGSGLszy1ojibmrSpDgmwqbUdNZRtJg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "L567LCB6OXMLMH3GNQAIRRVA2PZME3J2",
                            TwoFactorEnabled = false,
                            UserName = "ya"
                        },
                        new
                        {
                            Id = "58243206-3daf-48e2-ad79-9505d858a741",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fd86759e-a728-4301-bb4c-7a4bd0d76336",
                            Email = "melissas@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "MELISSAS@GMAIL.COM",
                            NormalizedUserName = "ME",
                            PasswordHash = "AQAAAAIAAYagAAAAEBi3bmCMzBOpBwvB3H4WRpPYkTTF4EAymmC5lvC0tDtcR3T0wSxP2V02PMjqVX0eXA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "KCMCB2Y5FBFRLSXVRVOR57G4L2TWH34U",
                            TwoFactorEnabled = false,
                            UserName = "me"
                        },
                        new
                        {
                            Id = "5fa062eb-77ff-4a87-a3a5-2e67baf727fe",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d0ea11d1-ccc0-463a-88f1-5fb5261438e8",
                            Email = "angelt@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "ANGELT@GMAIL.COM",
                            NormalizedUserName = "AN",
                            PasswordHash = "AQAAAAIAAYagAAAAEJOJnprX10E6HPvCGvqUNkQST5KMHVFKpUSYAIRa4dN4e4QlcSDpcLDZLsLBlzb7Vw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "STNJRBEA3GU6MYQBRQOEFLGKD3HNPBVU",
                            TwoFactorEnabled = false,
                            UserName = "an"
                        },
                        new
                        {
                            Id = "781e5335-f900-42c6-bdf4-fac0317f6e93",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "57a840e4-b8c1-4576-bd4a-1340fe4654cb",
                            Email = "eduardog@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "EDUARDOG@GMAIL.COM",
                            NormalizedUserName = "ED",
                            PasswordHash = "AQAAAAIAAYagAAAAEHoBR3pPzzaia+dxqUhTUidaWVMWN6pg2WlpWtvx0qDqbrvQ3y/bRcgMgdTGkHkYnA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "GUAH3AHJMPXADJBAZ3G5DMHLHNOXFKYP",
                            TwoFactorEnabled = false,
                            UserName = "ed"
                        },
                        new
                        {
                            Id = "78838dfd-5967-48f5-b021-d40ba2534420",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d5c22f09-206b-4881-9e6c-4e05c29f218a",
                            Email = "robertoa@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "ROBERTOA@GMAIL.COM",
                            NormalizedUserName = "RO",
                            PasswordHash = "AQAAAAIAAYagAAAAEDBNBqM/0WjbRLwzIKlBDrQ+wD0955oTp9piGthVheqGGYQkMQwkHjU4BnCwlMuQ7Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "SRBSEEET4CXMTP7DG5FBPU4HZN57ZNQA",
                            TwoFactorEnabled = false,
                            UserName = "ro"
                        },
                        new
                        {
                            Id = "79fc643e-6a9d-49b6-8d88-e34b30db128e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "690ead78-7316-4d85-8b49-8fb6c2e0d447",
                            Email = "erikal@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "ERIKAL@GMAIL.COM",
                            NormalizedUserName = "ER",
                            PasswordHash = "AQAAAAIAAYagAAAAEGUesq+GO7rZCWGG5uaMDtFzWwYA6Mc7BfHT3Kqw7fTOKvjBsNCOCftdG7gy17+YBQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "EIIAZJXNUPKW4U7PSVDWMH2R2PSWFLCZ",
                            TwoFactorEnabled = false,
                            UserName = "er"
                        },
                        new
                        {
                            Id = "8aa459a0-1d85-4d57-9fae-ce5f2a14f724",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "33427e9b-439d-474b-af9d-53aeb7afc432",
                            Email = "carlosr@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "CARLOSR@GMAIL.COM",
                            NormalizedUserName = "CA",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ2GQLjlQaeDA+4RvBLt22a9WwY9sPJdHTNnJ4Bjn2gLUTrzdbmKNSdMuNOWMuJm9w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "SW5K5NEPVYPUZ7YMSB2WOSNIJDVCV7B6",
                            TwoFactorEnabled = false,
                            UserName = "ca"
                        },
                        new
                        {
                            Id = "97ae5e15-8186-4973-b30f-db14f044ecd1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "63f2498c-efb6-48b0-8806-f31ba1272bde",
                            Email = "admin@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "AD",
                            PasswordHash = "AQAAAAIAAYagAAAAECbxfh2Xstsmcg8XS7lNIXyQLHKqSHIgCoiRYBU3HyKkD0ToJJHjB8QEDxC8ApKLZg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "WKXI4J3UH7JDYV3Z2UAZH42FJRI5XEK5",
                            TwoFactorEnabled = false,
                            UserName = "ad"
                        },
                        new
                        {
                            Id = "9af86b7a-507e-4926-869e-19d4b8308a90",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8db9eaa9-55bf-4a9f-9361-ac0784611b13",
                            Email = "juanh@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "JUANH@GMAIL.COM",
                            NormalizedUserName = "JU",
                            PasswordHash = "AQAAAAIAAYagAAAAEK/dZ2sdJFLerp0Pszdtmy9W0BrVZ5FSMdBNzOSBODRNtszmiEfnztsMy0Wf4gvO1g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "XPLMFC4J7JCJFFKOVE3WJ4EA2UUCDIPW",
                            TwoFactorEnabled = false,
                            UserName = "ju"
                        },
                        new
                        {
                            Id = "c5eb9a3e-9e53-4571-9722-8ef7f5b9adde",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9af6c859-7285-4afa-8cb6-b2f12da9bb89",
                            Email = "mauriciog@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "MAURICIOG@GMAIL.COM",
                            NormalizedUserName = "MA",
                            PasswordHash = "AQAAAAIAAYagAAAAEH3O0cXtfEesxc9NEdMz7sPPrscptLG53zF7pwcCHuR70yxANJ0Cnc0GZ27hInT6lA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "VFB3GMIGNMX4FN3BZI4QBROWBNUASHHD",
                            TwoFactorEnabled = false,
                            UserName = "ma"
                        },
                        new
                        {
                            Id = "d8216863-0000-4786-9d35-2211760bbe49",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3fb2a60b-5186-407e-9590-927803f1bc6e",
                            Email = "alanf@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "ALANF@GMAIL.COM",
                            NormalizedUserName = "AL",
                            PasswordHash = "AQAAAAIAAYagAAAAEOg67tu4zWwFXczSRahki5kueIITKKiaO5GiNPPe4EMSaFp/QkvnLtSR14ZEwUC3Lg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "FVCI754PQ7O7HEXBLA4UFJFJCLG7WGXX",
                            TwoFactorEnabled = false,
                            UserName = "al"
                        },
                        new
                        {
                            Id = "e68d4af8-8674-4949-8be4-0667112cc4a8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "dded809a-8d66-44d8-b495-cc80d82bf964",
                            Email = "adrianh@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "ADRIANH@GMAIL.COM",
                            NormalizedUserName = "ADR",
                            PasswordHash = "AQAAAAIAAYagAAAAEFEwvrirTZu6Y6pHxH6NNnfxp3w9KlD0TI6N49YsJNYCnKb5rT1ajtDL9mKoa0BD8g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "QMFHQDBFU7YL2QIF756DTJ4XHK4C3R74",
                            TwoFactorEnabled = false,
                            UserName = "adr"
                        });
                });

            modelBuilder.Entity("CletusReyes.Models.Domain_Model.Auth.TblUserRoles", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("CletusReyes.Models.Domain_Model.Category.TblCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Created_at")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Updated_at")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserIdCreated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserIdUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ffbf969b-36bb-47b3-a3ee-840523779c01"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Name = "GUANTES",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("3f98d5d2-f4be-4e0a-9b07-07f212973b0d"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Name = "PROTECCION",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("68598c64-99c6-487c-b0f8-c0044c137596"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Name = "COSTALES DE BOX",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("f63758e5-61e2-4bf3-925c-0cf137216fe6"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Name = "COACHING",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("35e3e543-5807-4805-890e-1d257fbeeee7"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Name = "ROPA Y CALZADO",
                            Status = true
                        });
                });

            modelBuilder.Entity("CletusReyes.Models.Domain_Model.Person.TblPerson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Birthday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("CletusReyes.Models.Domain_Model.Product.TblProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Created_at")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSizeInBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("MaxValue")
                        .HasColumnType("int");

                    b.Property<int>("MinValue")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("SizeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Updated_at")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserIdCreated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserIdUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SizeId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("05ca4c98-738a-47d0-ad57-0837f79042d6"),
                            CategoryId = new Guid("ffbf969b-36bb-47b3-a3ee-840523779c01"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Description = "",
                            FileDescription = "",
                            FileExtension = ".jpg",
                            FileName = "Guantesrojos16oz",
                            FilePath = "https://localhost:7088/Images/Guantesrojos16oz.jpg",
                            FileSizeInBytes = 0L,
                            MaxValue = 15,
                            MinValue = 3,
                            Name = "Guantes rojos 16oz",
                            Price = 1250.0,
                            Quantity = 10,
                            SizeId = new Guid("24d0f481-814c-41b3-b0d8-4c875d89a95d"),
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("6cbd63b4-f0c6-4cc8-99ca-6263e150e474"),
                            CategoryId = new Guid("ffbf969b-36bb-47b3-a3ee-840523779c01"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Description = "",
                            FileDescription = "",
                            FileExtension = ".jpg",
                            FileName = "Guantesnegros16oz",
                            FilePath = "https://localhost:7088/Images/Guantesnegros16oz.jpg",
                            FileSizeInBytes = 0L,
                            MaxValue = 20,
                            MinValue = 5,
                            Name = "Guantes negros 16oz",
                            Price = 1150.0,
                            Quantity = 10,
                            SizeId = new Guid("24d0f481-814c-41b3-b0d8-4c875d89a95d"),
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("fc000f09-4a69-4937-b7b0-80215b37de73"),
                            CategoryId = new Guid("ffbf969b-36bb-47b3-a3ee-840523779c01"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Description = "",
                            FileDescription = "",
                            FileExtension = ".jpeg",
                            FileName = "Guantesblancos16oz",
                            FilePath = "https://localhost:7088/Images/Guantesblancos16oz.jpeg",
                            FileSizeInBytes = 0L,
                            MaxValue = 20,
                            MinValue = 5,
                            Name = "Guantes blancos 16oz",
                            Price = 1150.0,
                            Quantity = 10,
                            SizeId = new Guid("24d0f481-814c-41b3-b0d8-4c875d89a95d"),
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("b9aa5ff6-9eac-4853-aaef-3e9ac0e77329"),
                            CategoryId = new Guid("ffbf969b-36bb-47b3-a3ee-840523779c01"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Description = "",
                            FileDescription = "",
                            FileExtension = ".jpg",
                            FileName = "Guantesdorados16oz",
                            FilePath = "https://localhost:7088/Images/Guantesdorados16oz.jpg",
                            FileSizeInBytes = 0L,
                            MaxValue = 15,
                            MinValue = 1,
                            Name = "Guantes dorados 16oz",
                            Price = 1600.0,
                            Quantity = 7,
                            SizeId = new Guid("24d0f481-814c-41b3-b0d8-4c875d89a95d"),
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("45715fa2-fdb2-4ced-8c21-76d71f374037"),
                            CategoryId = new Guid("ffbf969b-36bb-47b3-a3ee-840523779c01"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Description = "",
                            FileDescription = "",
                            FileExtension = ".png",
                            FileName = "Guantesrojos14oz",
                            FilePath = "https://localhost:7088/Images/Guantesrojos14oz.png",
                            FileSizeInBytes = 0L,
                            MaxValue = 12,
                            MinValue = 2,
                            Name = "Guantes rojos 14oz",
                            Price = 1300.0,
                            Quantity = 8,
                            SizeId = new Guid("1afcad04-bae2-4edd-a936-7eea79380149"),
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("b028a88c-80ea-4b62-8a45-4059d5dedf01"),
                            CategoryId = new Guid("ffbf969b-36bb-47b3-a3ee-840523779c01"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Description = "",
                            FileDescription = "",
                            FileExtension = ".jpg",
                            FileName = "Guantesnegros14oz",
                            FilePath = "https://localhost:7088/Images/Guantesnegros14oz.jpg",
                            FileSizeInBytes = 0L,
                            MaxValue = 11,
                            MinValue = 3,
                            Name = "Guantes negros 14oz",
                            Price = 1250.0,
                            Quantity = 8,
                            SizeId = new Guid("1afcad04-bae2-4edd-a936-7eea79380149"),
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("6aa0de18-fa8b-4070-a4dc-79cec6e1e700"),
                            CategoryId = new Guid("ffbf969b-36bb-47b3-a3ee-840523779c01"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Description = "",
                            FileDescription = "",
                            FileExtension = ".jpg",
                            FileName = "Guantesblancos14oz",
                            FilePath = "https://localhost:7088/Images/Guantesblancos14oz.jpg",
                            FileSizeInBytes = 0L,
                            MaxValue = 11,
                            MinValue = 3,
                            Name = "Guantes blancos 14oz",
                            Price = 1250.0,
                            Quantity = 8,
                            SizeId = new Guid("1afcad04-bae2-4edd-a936-7eea79380149"),
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("1432c9e0-c549-4e9d-8586-a8cabc81fbae"),
                            CategoryId = new Guid("ffbf969b-36bb-47b3-a3ee-840523779c01"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Description = "",
                            FileDescription = "",
                            FileExtension = ".jpg",
                            FileName = "Guantesdorados14oz",
                            FilePath = "https://localhost:7088/Images/Guantesdorados14oz.jpg",
                            FileSizeInBytes = 0L,
                            MaxValue = 10,
                            MinValue = 1,
                            Name = "Guantes dorados 14oz",
                            Price = 1550.0,
                            Quantity = 6,
                            SizeId = new Guid("1afcad04-bae2-4edd-a936-7eea79380149"),
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("9591d94e-2a82-49c5-ad1f-2dd1b7fa6837"),
                            CategoryId = new Guid("ffbf969b-36bb-47b3-a3ee-840523779c01"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Description = "",
                            FileDescription = "",
                            FileExtension = ".jpeg",
                            FileName = "Guantesrojos12oz",
                            FilePath = "https://localhost:7088/Images/Guantesrojos12oz.jpeg",
                            FileSizeInBytes = 0L,
                            MaxValue = 10,
                            MinValue = 2,
                            Name = "Guantes rojos 12oz",
                            Price = 1400.0,
                            Quantity = 6,
                            SizeId = new Guid("4847982e-f6e4-4d30-acfa-d4d3eb774025"),
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("d13a1ae6-4dc0-4bb3-bf1d-184ac3d18885"),
                            CategoryId = new Guid("ffbf969b-36bb-47b3-a3ee-840523779c01"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Description = "",
                            FileDescription = "",
                            FileExtension = ".jpeg",
                            FileName = "Guantesnegros12oz",
                            FilePath = "https://localhost:7088/Images/Guantesnegros12oz.jpeg",
                            FileSizeInBytes = 0L,
                            MaxValue = 13,
                            MinValue = 4,
                            Name = "Guantes negros 12oz",
                            Price = 1000.0,
                            Quantity = 6,
                            SizeId = new Guid("4847982e-f6e4-4d30-acfa-d4d3eb774025"),
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("9d1801c2-52f1-425d-bf45-67eedcfc4179"),
                            CategoryId = new Guid("ffbf969b-36bb-47b3-a3ee-840523779c01"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Description = "",
                            FileDescription = "",
                            FileExtension = ".jpg",
                            FileName = "Guantesblancos12oz",
                            FilePath = "https://localhost:7088/Images/Guantesblancos12oz.jpeg",
                            FileSizeInBytes = 0L,
                            MaxValue = 10,
                            MinValue = 2,
                            Name = "Guantes blancos 12oz",
                            Price = 1400.0,
                            Quantity = 6,
                            SizeId = new Guid("4847982e-f6e4-4d30-acfa-d4d3eb774025"),
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("4175f4ae-4750-4ceb-bfa8-7ff83b0a1d7e"),
                            CategoryId = new Guid("ffbf969b-36bb-47b3-a3ee-840523779c01"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Description = "",
                            FileDescription = "",
                            FileExtension = ".jpg",
                            FileName = "Guantesdorados12oz",
                            FilePath = "https://localhost:7088/Images/Guantesdorados12oz.jpeg",
                            FileSizeInBytes = 0L,
                            MaxValue = 8,
                            MinValue = 1,
                            Name = "Guantes dorados 12oz",
                            Price = 1500.0,
                            Quantity = 1,
                            SizeId = new Guid("4847982e-f6e4-4d30-acfa-d4d3eb774025"),
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("e1095653-b2fd-46c1-8f54-3c4d30a9401a"),
                            CategoryId = new Guid("3f98d5d2-f4be-4e0a-9b07-07f212973b0d"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Description = "",
                            FileDescription = "",
                            FileExtension = ".jpg",
                            FileName = "Caretarojaadulto",
                            FilePath = "https://localhost:7088/Images/Caretarojaadulto.jpg",
                            FileSizeInBytes = 0L,
                            MaxValue = 25,
                            MinValue = 5,
                            Name = "Careta roja adulto",
                            Price = 1000.0,
                            Quantity = 10,
                            SizeId = new Guid("515d8c75-f2f2-4473-8f82-405dedb5d613"),
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("6528d6ce-e99c-4a78-99f7-20201d8c8aa3"),
                            CategoryId = new Guid("3f98d5d2-f4be-4e0a-9b07-07f212973b0d"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Description = "",
                            FileDescription = "",
                            FileExtension = ".jpg",
                            FileName = "Caretanegraadulto",
                            FilePath = "https://localhost:7088/Images/Caretanegraadulto.jpg",
                            FileSizeInBytes = 0L,
                            MaxValue = 25,
                            MinValue = 5,
                            Name = "Careta negra adulto",
                            Price = 1000.0,
                            Quantity = 10,
                            SizeId = new Guid("515d8c75-f2f2-4473-8f82-405dedb5d613"),
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("fca25f2b-ec65-4e45-9c4b-9c2351ccebed"),
                            CategoryId = new Guid("3f98d5d2-f4be-4e0a-9b07-07f212973b0d"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Description = "",
                            FileDescription = "",
                            FileExtension = ".jpg",
                            FileName = "Caretablancaadulto",
                            FilePath = "https://localhost:7088/Images/Caretablancaadulto.jpg",
                            FileSizeInBytes = 0L,
                            MaxValue = 25,
                            MinValue = 5,
                            Name = "Careta blanca adulto",
                            Price = 1000.0,
                            Quantity = 10,
                            SizeId = new Guid("515d8c75-f2f2-4473-8f82-405dedb5d613"),
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("2ae73b97-e8a8-4de2-9ad7-e0fbfc583677"),
                            CategoryId = new Guid("3f98d5d2-f4be-4e0a-9b07-07f212973b0d"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Description = "",
                            FileDescription = "",
                            FileExtension = ".jpg",
                            FileName = "Caretarojachica",
                            FilePath = "https://localhost:7088/Images/Caretarojachica.jpg",
                            FileSizeInBytes = 0L,
                            MaxValue = 25,
                            MinValue = 5,
                            Name = "Careta roja chica",
                            Price = 1000.0,
                            Quantity = 10,
                            SizeId = new Guid("98838e4b-fae5-4ae8-9cc3-05b794dc322e"),
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("94c66e3f-9138-4e41-8bf0-8a31c2241262"),
                            CategoryId = new Guid("3f98d5d2-f4be-4e0a-9b07-07f212973b0d"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Description = "",
                            FileDescription = "",
                            FileExtension = ".jpg",
                            FileName = "Caretanegrachica",
                            FilePath = "https://localhost:7088/Images/Caretanegrachica.jpg",
                            FileSizeInBytes = 0L,
                            MaxValue = 25,
                            MinValue = 5,
                            Name = "Careta negra chica",
                            Price = 1000.0,
                            Quantity = 10,
                            SizeId = new Guid("98838e4b-fae5-4ae8-9cc3-05b794dc322e"),
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("17ed600e-4634-474d-b58d-a20085f0fa05"),
                            CategoryId = new Guid("3f98d5d2-f4be-4e0a-9b07-07f212973b0d"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Description = "",
                            FileDescription = "",
                            FileExtension = ".jpg",
                            FileName = "Caretablancachica",
                            FilePath = "https://localhost:7088/Images/Caretablancachica.jpg",
                            FileSizeInBytes = 0L,
                            MaxValue = 25,
                            MinValue = 5,
                            Name = "Careta blanca chica",
                            Price = 1000.0,
                            Quantity = 10,
                            SizeId = new Guid("98838e4b-fae5-4ae8-9cc3-05b794dc322e"),
                            Status = true
                        });
                });

            modelBuilder.Entity("CletusReyes.Models.Domain_Model.Provider.TblProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Created_at")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Updated_at")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserIdCreated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserIdUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Providers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("32a9172e-d7fd-4b44-83cc-48bfed5a80a1"),
                            Address = "Blvd. Torres Landa #3301 Col.Arroyo Hondo",
                            BusinessName = "Medina Torres",
                            ContactEmail = "info@medinatorres.com",
                            ContactName = "Juan Medina",
                            ContactPhone = "4777181780",
                            Created_at = "8/15/2023 6:40:14 PM",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("e1174f5b-5e16-4bc1-8c31-7e8e89e6022e"),
                            Address = "Monte Carmelo #112 Col.Arroyo Hondo",
                            BusinessName = "Curtiembres de México",
                            ContactEmail = "info@curtiembresdemexico.com",
                            ContactName = "Sebastian Perez",
                            ContactPhone = "4777780079",
                            Created_at = "8/15/2023 6:40:14 PM",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("cc1fa6e7-bee4-4e34-b427-f26ebb6314c8"),
                            Address = "Av.Transportistas #301 Col.Unidad Obrera",
                            BusinessName = "Lefarc",
                            ContactEmail = "mercadotecnia@lefarc.com",
                            ContactName = "Alonso Hernandez",
                            ContactPhone = "4774702828",
                            Created_at = "8/15/2023 6:40:14 PM",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("66398fad-6c5a-4608-9a3e-dc9b58be6cf5"),
                            Address = "Blvd.Timoteo Lozano #101-B Col.San Miguel",
                            BusinessName = "Simon Quimica",
                            ContactEmail = "ventassq@simonquimica.mx",
                            ContactName = "Erika Serrato",
                            ContactPhone = "4777705252",
                            Created_at = "8/15/2023 6:40:14 PM",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("753ff726-1613-4e81-b936-39ecd53259d1"),
                            Address = "Boulevard Prolongación Tepeyac #1304 local 2 Col. Prados Verdes",
                            BusinessName = "Velcro Brand",
                            ContactEmail = "btlalolini@prodigy.net.mx",
                            ContactName = "Bruno Tlalolini",
                            ContactPhone = "4777747540",
                            Created_at = "8/15/2023 6:40:14 PM",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("4e097db4-5534-4d4b-b16c-4ce2550d9d32"),
                            Address = "Blvd.Antonio Madrazo #1216 Col.El Cortijo",
                            BusinessName = "Espumax",
                            ContactEmail = "espumax@gmail.com",
                            ContactName = "Ivan Sanchez",
                            ContactPhone = "4772335162",
                            Created_at = "8/15/2023 6:40:14 PM",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("2802ecd1-0b0f-46d0-8cd8-bb94be233e9e"),
                            Address = "Blvd. Hermenegildo Bustos #2217 col.Unidad Obrera Infonavit",
                            BusinessName = "Hilos Modiz",
                            ContactEmail = "modiz@gmail.com",
                            ContactName = "Araceli Gutierrez",
                            ContactPhone = "4777180275",
                            Created_at = "8/15/2023 6:40:14 PM",
                            Status = true
                        });
                });

            modelBuilder.Entity("CletusReyes.Models.Domain_Model.Purchase_Order.TblPurchaseOrderDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<Guid>("PurchaseOrderHeaderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Quantity")
                        .HasColumnType("real");

                    b.Property<Guid>("RawMaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseOrderHeaderId");

                    b.HasIndex("RawMaterialId");

                    b.ToTable("PurchaseOrderDetails");
                });

            modelBuilder.Entity("CletusReyes.Models.Domain_Model.Purchase_Order.TblPurchaseOrderHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Created_at")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PurchaseOrderStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<float>("Total")
                        .HasColumnType("real");

                    b.Property<string>("Updated_at")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserIdCreated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserIdUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.HasIndex("PurchaseOrderStatusId");

                    b.ToTable("PurchaseOrderHeaders");
                });

            modelBuilder.Entity("CletusReyes.Models.Domain_Model.Purchase_Order.TblPurchaseOrderStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Created_at")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Updated_at")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserIdCreated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserIdUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PurchaseOrderStatus");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6967f493-61ef-41af-b785-a9a8649e8767"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Name = "SOLICITADA",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("e2d2d115-764b-4264-a6a9-4a1f4d5f4dd4"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Name = "EN CAMINO",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("5e257c72-e959-4d0d-9894-1c8682515a3a"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Name = "ENTREGADA",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("196f0047-4231-4160-8d4e-124b8437dfac"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Name = "CANCELADA",
                            Status = true
                        });
                });

            modelBuilder.Entity("CletusReyes.Models.Domain_Model.Raw_Material.TblRawMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Created_at")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("MaxValue")
                        .HasColumnType("real");

                    b.Property<float>("MinValue")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Quantity")
                        .HasColumnType("real");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<Guid>("UnitMeasureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Updated_at")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserIdCreated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserIdUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.HasIndex("UnitMeasureId");

                    b.ToTable("RawMaterials");

                    b.HasData(
                        new
                        {
                            Id = new Guid("758a1a4e-c7f8-4058-a7c4-2602c0298b32"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Description = "",
                            MaxValue = 30000f,
                            MinValue = 1500f,
                            Name = "Piel de vaca color rojo",
                            Price = 350.0,
                            ProviderId = new Guid("32a9172e-d7fd-4b44-83cc-48bfed5a80a1"),
                            Quantity = 15000f,
                            Status = true,
                            UnitMeasureId = new Guid("92743a31-78d1-4e8a-eb94-08db979fe8cb")
                        },
                        new
                        {
                            Id = new Guid("f11ccf0f-f8e9-4fda-8677-6992dd53a64b"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Description = "",
                            MaxValue = 20000f,
                            MinValue = 1000f,
                            Name = "Piel de vaca color negro",
                            Price = 325.0,
                            ProviderId = new Guid("32a9172e-d7fd-4b44-83cc-48bfed5a80a1"),
                            Quantity = 7000f,
                            Status = true,
                            UnitMeasureId = new Guid("92743a31-78d1-4e8a-eb94-08db979fe8cb")
                        },
                        new
                        {
                            Id = new Guid("72294d1e-133a-4c69-9eb9-df383ad49819"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Description = "",
                            MaxValue = 25000f,
                            MinValue = 2000f,
                            Name = "Piel de vaca color dorado",
                            Price = 450.0,
                            ProviderId = new Guid("32a9172e-d7fd-4b44-83cc-48bfed5a80a1"),
                            Quantity = 12000f,
                            Status = true,
                            UnitMeasureId = new Guid("92743a31-78d1-4e8a-eb94-08db979fe8cb")
                        },
                        new
                        {
                            Id = new Guid("5eb8fffa-c508-47a6-a662-0452993ea114"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Description = "",
                            MaxValue = 40000f,
                            MinValue = 2000f,
                            Name = "Piel de vaca color blanco",
                            Price = 375.0,
                            ProviderId = new Guid("32a9172e-d7fd-4b44-83cc-48bfed5a80a1"),
                            Quantity = 20000f,
                            Status = true,
                            UnitMeasureId = new Guid("92743a31-78d1-4e8a-eb94-08db979fe8cb")
                        },
                        new
                        {
                            Id = new Guid("dff9d777-3531-4d9c-abcf-78f4fbff80fa"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Description = "",
                            MaxValue = 100000f,
                            MinValue = 2000f,
                            Name = "Piel sintetica color negro",
                            Price = 150.0,
                            ProviderId = new Guid("66398fad-6c5a-4608-9a3e-dc9b58be6cf5"),
                            Quantity = 3500f,
                            Status = true,
                            UnitMeasureId = new Guid("92743a31-78d1-4e8a-eb94-08db979fe8cb")
                        },
                        new
                        {
                            Id = new Guid("d9fd1206-ccf1-44e6-979d-0d2dac1bccbd"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Description = "",
                            MaxValue = 10000f,
                            MinValue = 200f,
                            Name = "Piel sintetica color rojo",
                            Price = 125.0,
                            ProviderId = new Guid("66398fad-6c5a-4608-9a3e-dc9b58be6cf5"),
                            Quantity = 3500f,
                            Status = true,
                            UnitMeasureId = new Guid("92743a31-78d1-4e8a-eb94-08db979fe8cb")
                        },
                        new
                        {
                            Id = new Guid("3bb6c3af-9fcc-462e-9f31-b7a20fd413d4"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Description = "",
                            MaxValue = 9000f,
                            MinValue = 200f,
                            Name = "Piel sintetica color blanco",
                            Price = 100.0,
                            ProviderId = new Guid("66398fad-6c5a-4608-9a3e-dc9b58be6cf5"),
                            Quantity = 3500f,
                            Status = true,
                            UnitMeasureId = new Guid("92743a31-78d1-4e8a-eb94-08db979fe8cb")
                        },
                        new
                        {
                            Id = new Guid("d4736685-9730-40fd-a18e-5d7bdff280e2"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Description = "",
                            MaxValue = 11000f,
                            MinValue = 500f,
                            Name = "Piel sintetica color dorado",
                            Price = 200.0,
                            ProviderId = new Guid("66398fad-6c5a-4608-9a3e-dc9b58be6cf5"),
                            Quantity = 3500f,
                            Status = true,
                            UnitMeasureId = new Guid("92743a31-78d1-4e8a-eb94-08db979fe8cb")
                        },
                        new
                        {
                            Id = new Guid("5ce0a50e-d43f-479c-a51d-5792c2405555"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Description = "",
                            MaxValue = 100f,
                            MinValue = 5f,
                            Name = "Goma espuma de 100*100cm",
                            Price = 350.0,
                            ProviderId = new Guid("4e097db4-5534-4d4b-b16c-4ce2550d9d32"),
                            Quantity = 56f,
                            Status = true,
                            UnitMeasureId = new Guid("7220fd18-43fe-4880-eb95-08db979fe8cb")
                        },
                        new
                        {
                            Id = new Guid("250b5182-f96d-422f-9efd-0afd55221143"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Description = "",
                            MaxValue = 10000f,
                            MinValue = 200f,
                            Name = "Hilo negro",
                            Price = 100.0,
                            ProviderId = new Guid("2802ecd1-0b0f-46d0-8cd8-bb94be233e9e"),
                            Quantity = 5000f,
                            Status = true,
                            UnitMeasureId = new Guid("92743a31-78d1-4e8a-eb94-08db979fe8cb")
                        },
                        new
                        {
                            Id = new Guid("0056c142-13f2-465d-824d-4299eaa3d45d"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Description = "",
                            MaxValue = 10000f,
                            MinValue = 200f,
                            Name = "Hilo blanco",
                            Price = 100.0,
                            ProviderId = new Guid("2802ecd1-0b0f-46d0-8cd8-bb94be233e9e"),
                            Quantity = 5000f,
                            Status = true,
                            UnitMeasureId = new Guid("92743a31-78d1-4e8a-eb94-08db979fe8cb")
                        },
                        new
                        {
                            Id = new Guid("db9e6ef4-d516-448d-9c40-1ba7b7b83af2"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Description = "",
                            MaxValue = 10000f,
                            MinValue = 200f,
                            Name = "Hilo rojo",
                            Price = 100.0,
                            ProviderId = new Guid("2802ecd1-0b0f-46d0-8cd8-bb94be233e9e"),
                            Quantity = 5000f,
                            Status = true,
                            UnitMeasureId = new Guid("92743a31-78d1-4e8a-eb94-08db979fe8cb")
                        },
                        new
                        {
                            Id = new Guid("bc94f5cf-8b87-4860-8fb4-a5794f06833d"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Description = "",
                            MaxValue = 10000f,
                            MinValue = 200f,
                            Name = "Hilo dorado",
                            Price = 100.0,
                            ProviderId = new Guid("2802ecd1-0b0f-46d0-8cd8-bb94be233e9e"),
                            Quantity = 5000f,
                            Status = true,
                            UnitMeasureId = new Guid("92743a31-78d1-4e8a-eb94-08db979fe8cb")
                        },
                        new
                        {
                            Id = new Guid("bb156abe-638f-4243-b338-5f7ed26d2f47"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Description = "Rollos de 100cm con 10cm de espesor",
                            MaxValue = 20000f,
                            MinValue = 500f,
                            Name = "Velcro negro",
                            Price = 250.0,
                            ProviderId = new Guid("753ff726-1613-4e81-b936-39ecd53259d1"),
                            Quantity = 5000f,
                            Status = true,
                            UnitMeasureId = new Guid("92743a31-78d1-4e8a-eb94-08db979fe8cb")
                        },
                        new
                        {
                            Id = new Guid("279b5ed0-e9e0-4e2c-88fd-176ad5b8847a"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Description = "Rollos de 100cm con 10cm de espesor",
                            MaxValue = 20000f,
                            MinValue = 500f,
                            Name = "Velcro rojo",
                            Price = 235.0,
                            ProviderId = new Guid("753ff726-1613-4e81-b936-39ecd53259d1"),
                            Quantity = 5000f,
                            Status = true,
                            UnitMeasureId = new Guid("92743a31-78d1-4e8a-eb94-08db979fe8cb")
                        },
                        new
                        {
                            Id = new Guid("83e4c615-648c-4405-aed6-bbd084ea105f"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Description = "Rollos de 100cm con 10cm de espesor",
                            MaxValue = 20000f,
                            MinValue = 500f,
                            Name = "Velcro blanco",
                            Price = 235.0,
                            ProviderId = new Guid("753ff726-1613-4e81-b936-39ecd53259d1"),
                            Quantity = 5000f,
                            Status = true,
                            UnitMeasureId = new Guid("92743a31-78d1-4e8a-eb94-08db979fe8cb")
                        });
                });

            modelBuilder.Entity("CletusReyes.Models.Domain_Model.Recipe.TblRecipeDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Quantity")
                        .HasColumnType("real");

                    b.Property<Guid>("RawMaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RecipeHeaderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RawMaterialId");

                    b.HasIndex("RecipeHeaderId");

                    b.ToTable("RecipeDetails");
                });

            modelBuilder.Entity("CletusReyes.Models.Domain_Model.Recipe.TblRecipeHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Created_at")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Updated_at")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserIdCreated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserIdUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("RecipeHeaders");
                });

            modelBuilder.Entity("CletusReyes.Models.Domain_Model.Sale_Order.TblSaleOrderDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("SaleOrderHeaderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleOrderHeaderId");

                    b.ToTable("SaleOrderDetails");
                });

            modelBuilder.Entity("CletusReyes.Models.Domain_Model.Sale_Order.TblSaleOrderHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Created_at")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SaleOrderStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<float>("Total")
                        .HasColumnType("real");

                    b.Property<string>("Updated_at")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserIdUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SaleOrderStatusId");

                    b.HasIndex("UserId");

                    b.ToTable("SaleOrderHeaders");
                });

            modelBuilder.Entity("CletusReyes.Models.Domain_Model.Sale_Order.TblSaleOrderStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Created_at")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Updated_at")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserIdCreated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserIdUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SaleOrderStatus");

                    b.HasData(
                        new
                        {
                            Id = new Guid("34e82473-b511-4b31-a94e-304130ee2ede"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Name = "PEDIDO",
                            Status = false
                        },
                        new
                        {
                            Id = new Guid("bf341b19-7e2e-492e-8aef-ebab9c33fe09"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Name = "ELABORANDO",
                            Status = false
                        },
                        new
                        {
                            Id = new Guid("aeb24d0e-7e62-4183-ace1-4401939ddce6"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Name = "EMPACANDO",
                            Status = false
                        },
                        new
                        {
                            Id = new Guid("25a4b068-bc82-4684-8bc5-5c4087d487e4"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Name = "ENVIANDO",
                            Status = false
                        },
                        new
                        {
                            Id = new Guid("d5f1c029-61cf-4273-a3d7-431c110e4f15"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Name = "ENTREGADO",
                            Status = false
                        },
                        new
                        {
                            Id = new Guid("cb22b5ba-8792-4675-88bb-e33beb098b7d"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Name = "CANCELADO",
                            Status = false
                        });
                });

            modelBuilder.Entity("CletusReyes.Models.Domain_Model.Size.TblSize", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Created_at")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Updated_at")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserIdCreated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserIdUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sizes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4847982e-f6e4-4d30-acfa-d4d3eb774025"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Size = "12oz",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("1afcad04-bae2-4edd-a936-7eea79380149"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Size = "14oz",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("24d0f481-814c-41b3-b0d8-4c875d89a95d"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Size = "16oz",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("98838e4b-fae5-4ae8-9cc3-05b794dc322e"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Size = "CHICO",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("515d8c75-f2f2-4473-8f82-405dedb5d613"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Size = "ADULTO",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("e38bff0e-b36d-4dd6-99b6-c23ee4e4a05a"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Size = "NO APLICA",
                            Status = true
                        });
                });

            modelBuilder.Entity("CletusReyes.Models.Domain_Model.Unit_Measure.TblUnitMeasure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Created_at")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Updated_at")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserIdCreated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserIdUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UnitMeasures");

                    b.HasData(
                        new
                        {
                            Id = new Guid("92743a31-78d1-4e8a-eb94-08db979fe8cb"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Name = "CM",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("7220fd18-43fe-4880-eb95-08db979fe8cb"),
                            Created_at = "8/15/2023 6:40:14 PM",
                            Name = "PZ",
                            Status = true
                        });
                });

            modelBuilder.Entity("CletusReyes.Models.Domain_Model.Auth.TblUserRoles", b =>
                {
                    b.HasOne("CletusReyes.Models.Domain_Model.Auth.TblRoles", "Roles")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CletusReyes.Models.Domain_Model.Auth.TblUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roles");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CletusReyes.Models.Domain_Model.Person.TblPerson", b =>
                {
                    b.HasOne("CletusReyes.Models.Domain_Model.Auth.TblUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CletusReyes.Models.Domain_Model.Product.TblProduct", b =>
                {
                    b.HasOne("CletusReyes.Models.Domain_Model.Category.TblCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CletusReyes.Models.Domain_Model.Size.TblSize", "Size")
                        .WithMany()
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("CletusReyes.Models.Domain_Model.Purchase_Order.TblPurchaseOrderDetail", b =>
                {
                    b.HasOne("CletusReyes.Models.Domain_Model.Purchase_Order.TblPurchaseOrderHeader", "PurchaseOrderHeader")
                        .WithMany("Details")
                        .HasForeignKey("PurchaseOrderHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CletusReyes.Models.Domain_Model.Raw_Material.TblRawMaterial", "RawMaterial")
                        .WithMany()
                        .HasForeignKey("RawMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PurchaseOrderHeader");

                    b.Navigation("RawMaterial");
                });

            modelBuilder.Entity("CletusReyes.Models.Domain_Model.Purchase_Order.TblPurchaseOrderHeader", b =>
                {
                    b.HasOne("CletusReyes.Models.Domain_Model.Provider.TblProvider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CletusReyes.Models.Domain_Model.Purchase_Order.TblPurchaseOrderStatus", "PurchaseOrderStatus")
                        .WithMany()
                        .HasForeignKey("PurchaseOrderStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");

                    b.Navigation("PurchaseOrderStatus");
                });

            modelBuilder.Entity("CletusReyes.Models.Domain_Model.Raw_Material.TblRawMaterial", b =>
                {
                    b.HasOne("CletusReyes.Models.Domain_Model.Provider.TblProvider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CletusReyes.Models.Domain_Model.Unit_Measure.TblUnitMeasure", "UnitMeasure")
                        .WithMany()
                        .HasForeignKey("UnitMeasureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");

                    b.Navigation("UnitMeasure");
                });

            modelBuilder.Entity("CletusReyes.Models.Domain_Model.Recipe.TblRecipeDetail", b =>
                {
                    b.HasOne("CletusReyes.Models.Domain_Model.Raw_Material.TblRawMaterial", "RawMaterial")
                        .WithMany()
                        .HasForeignKey("RawMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CletusReyes.Models.Domain_Model.Recipe.TblRecipeHeader", "RecipeHeader")
                        .WithMany("Details")
                        .HasForeignKey("RecipeHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RawMaterial");

                    b.Navigation("RecipeHeader");
                });

            modelBuilder.Entity("CletusReyes.Models.Domain_Model.Recipe.TblRecipeHeader", b =>
                {
                    b.HasOne("CletusReyes.Models.Domain_Model.Product.TblProduct", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CletusReyes.Models.Domain_Model.Sale_Order.TblSaleOrderDetail", b =>
                {
                    b.HasOne("CletusReyes.Models.Domain_Model.Product.TblProduct", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CletusReyes.Models.Domain_Model.Sale_Order.TblSaleOrderHeader", "SaleOrderHeader")
                        .WithMany("Details")
                        .HasForeignKey("SaleOrderHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("SaleOrderHeader");
                });

            modelBuilder.Entity("CletusReyes.Models.Domain_Model.Sale_Order.TblSaleOrderHeader", b =>
                {
                    b.HasOne("CletusReyes.Models.Domain_Model.Sale_Order.TblSaleOrderStatus", "SaleOrderStatus")
                        .WithMany()
                        .HasForeignKey("SaleOrderStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CletusReyes.Models.Domain_Model.Auth.TblUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SaleOrderStatus");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CletusReyes.Models.Domain_Model.Auth.TblRoles", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("CletusReyes.Models.Domain_Model.Auth.TblUser", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("CletusReyes.Models.Domain_Model.Purchase_Order.TblPurchaseOrderHeader", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("CletusReyes.Models.Domain_Model.Recipe.TblRecipeHeader", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("CletusReyes.Models.Domain_Model.Sale_Order.TblSaleOrderHeader", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
