// <auto-generated />
using CletusReyes.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CletusReyes.Migrations.CletusReyesDataMigrations
{
    [DbContext(typeof(CletusReyesData))]
    [Migration("20230816173201_First migration")]
    partial class Firstmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CletusReyes.Models.Domain_Model.Analytical.TblClientesVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<string>("NombrePersona")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalVentas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ClientesVentas");
                });

            modelBuilder.Entity("CletusReyes.Models.Domain_Model.Analytical.TblMateriaComprada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<string>("NombreMateria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("SumaMateria")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("MateriaComprada");
                });

            modelBuilder.Entity("CletusReyes.Models.Domain_Model.Analytical.TblProductosVendidos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("SumaProductos")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("ProductosVendidos");
                });

            modelBuilder.Entity("CletusReyes.Models.Domain_Model.Analytical.TblProveedoresCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<string>("NombreProveedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("TotalCompras")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("ProveedoresCompras");
                });

            modelBuilder.Entity("CletusReyes.Models.Domain_Model.Analytical.TblTotalCompras", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<int>("TotalCompras")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TotalCompras");
                });

            modelBuilder.Entity("CletusReyes.Models.Domain_Model.Analytical.TblTotalGastos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<float>("TotalGastos")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("TotalGastos");
                });

            modelBuilder.Entity("CletusReyes.Models.Domain_Model.Analytical.TblTotalIngresos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<float>("TotalIngresos")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("TotalIngresos");
                });

            modelBuilder.Entity("CletusReyes.Models.Domain_Model.Analytical.TblTotalVentas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<int>("TotalVentas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TotalVentas");
                });
#pragma warning restore 612, 618
        }
    }
}
